---
providers:
  yaml:
    class: octodns.provider.yaml.YamlProvider
    directory: ./example
    default_ttl: 3600
    enforce_order: False
  pihole:
    class: octodns_pihole.PiholeProvider
    url: http://127.0.0.1
    password: "correct horse battery staple"  # for example only! use env/PIHOLE_PASSWORD
    strict_supports: false # ignore unsupported records

zones:
  example.tld.:
    sources:
      - yaml
    targets:
      - pihole
